(*
 * This file was automatically generated by MDGen (v2.0)
 * from the machine description file "x86/x86.md".
 *)


functor X86RTL(BuildRTL : BUILD_RTL
)= struct
   local
      open BuildRTL
   in
   end
end

