#!/bin/sh
# hack to build the source dist
CVSROOT=":pserver:cvs@vista.cs.princeton.edu:/cvsroot"
PACKAGE=asdlGen
VERSION=$1
RELEASE=$2
TMPDIR=/usr/tmp/
NAME=${PACKAGE}-${VERSION}-${RELEASE}
REV=today
DISTDIR=${TMPDIR}/${PACKAGE}-${VERSION}
cd ${TMPDIR}
# build the source dist first
rm -rf ${NAME}.src.tar.gz ${PACKAGE}-${VERSION}

cvs  -d ${CVSROOT} export -d ${PACKAGE}-${VERSION} -D${REV} ${PACKAGE}

# build the documentation
mkdir ${DISTDIR}/doc
cd ${DISTDIR}/doc
sgml2latex -p letter -o ps -P "\usepackage{pslatex}" \
	${DISTDIR}/src/doc/manual.sgml

mkdir ${DISTDIR}/doc/html
cd ${DISTDIR}/doc/html
sgml2html ${DISTDIR}/src/doc/manual.sgml

# build toplevel readmes etc...
cd ${DISTDIR}
for file in *.sgml ; do
   sgml2html -s 0 ${file}
   sgml2txt -f ${file}
   fbase=`basename ${file} .sgml`
   mv ${fbase}.txt $fbase
done

cd ${TMPDIR}
tar cf ${NAME}.src.tar ${PACKAGE}-${VERSION}
gzip ${NAME}.src.tar