#! /bin/sh
# Generated automatically from sml-batch.in by configure.
cmfile=sources-$$.cm
cat > ${cmfile} <<EOF
Group  is
$@
EOF
sml-cm <<EOF
((CM.make' ("${cmfile}") handle _ => OS.Process.exit OS.Process.failure);
    OS.Process.exit OS.Process.success; ())
EOF
ret=$?
rm -rf ${cmfile} CM
exit $ret
